linters:
  enable-all: true
  disable:
    # First, disable deprecated linters
    - interfacer
    - golint
    - scopelint

    # We use long functions
    - cyclop
    # We have some utility unused functions
    - deadcode
    # Reports false positives
    - dupl
    # We don't need to initialize every value of a struct
    - exhaustivestruct
    # We use print statements
    - forbidigo
    # We do not need to check every type assertion
    - forcetypeassert
    # We use long functions
    - funlen
    # We use globals in the code base
    - gochecknoglobals
    # gocognit complains about having large functions
    - gocognit
    # goconst complains about common strings
    - goconst
    # gocritic complains about needing to make case statements
    - gocritic
    # gocyclo complains about having large functions
    - gocyclo
    # We do not use conventional Golang comments
    - godot
    # goerr113 complains about creating new static errors
    - goerr113
    # gofumpt is not used
    - gofumpt
    # gomnd complains about magic numbers
    - gomnd
    # We declare variables at the beginning of a function for consistency
    - ifshort
    # We manage long lines manually
    - lll
    # We do not care about making structs take less memory
    - maligned
    # nestif complains about some harmless nested if statements
    - nestif
    # nlreturn requires about excessive newlines around return statements
    - nlreturn
    # We do not need to use contexts in certain situations
    - noctx
    # TODO
    - nosnakecase
    # We use some unused parameters for command function uniformity
    - unparam
    # We have some utility unused functions
    - unused
    # We don't need to wrap all errors
    - wrapcheck
    # WSL requires excessive newlines around if statements
    - wsl

issues:
  # We want to use golint but we don't care about some of the things that it complains about
  exclude:
    # We have many exported functions without comments
    - "exported \\w+ (\\S*['.]*)([a-zA-Z'.*]*) should have comment or be unexported"
    # We block-scope variables in many places, making it impossible to outdent
    - "if block ends with a return statement, so drop this else and outdent its block"
    # TODO in comments is okay
    - "Line contains TODO/BUG/FIXME"

linters-settings:
  govet:
    # Checking for shadowed variables is experimental and disabled by default
    check-shadowing: true

  whitespace:
    # Enforce newlines (or comments) after every multi-line if statement
    multi-if: true
